# Generated by Django 5.2.9 on 2026-09-07 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labreport',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddIndex(
            model_name='labreport',
            index=models.Index(fields=['user', '-uploaded_at'], name='lab_labrepo_user_id_d685b7_idx'),
        ),
    ]
